
[GHEGist]
  Public = false
  access_token = ""
  auto_sync = false
  base_url = ""
  file_name = ""
  gist_id = ""
  upload_url = ""

[General]
  Backend = "gist"
  Cmd = []
  Color = false
  Column = 40
  Editor = "micro"
  Format = "[$description]: $command $tags"
  SelectCmd = "fzf --ansi --layout=reverse --border --height=90% --pointer=* --cycle --prompt=Snippets:"
  SnippetDirs = []
  SnippetFile = "~/.config/pet/snippet.toml"
  SortBy = ""

[Gist]
  Public = false
  access_token = ""
  auto_sync = true
  file_name = "pet-snippet.toml"
  gist_id = "755f1cf7c9d94414bd54573fcfa61e82"

[GitLab]
  ID = ""
  Url = ""
  Visibility = "private"
  access_token = ""
  auto_sync = false
  file_name = "pet-snippet.toml"
  skip_ssl = false
