---
- name: Weekly maintenance stack (with cleanup)
  hosts: Linux
  gather_facts: no
  serial: 1
  any_errors_fatal: true
  tasks:
    - name: chezmoi update
      ansible.builtin.command: chezmoi update
      register: result
      failed_when: result.rc != 0

    - name: dcms
      ansible.builtin.command: dcms
      register: result
      failed_when: result.rc != 0

    - name: upd -cy (with cleanup)
      ansible.builtin.command: 'upd -cy'
      register: result
      failed_when: result.rc != 0
